// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity ^0.8.22;

import { Script } from "forge-std/Script.sol";
import { console } from "forge-std/console.sol";
import { IERC20 } from "forge-std/interfaces/IERC20.sol";

import { InputSettlerBase } from "../../src/input/InputSettlerBase.sol";
import { InputSettlerEscrow } from "../../src/input/escrow/InputSettlerEscrow.sol";
import { PolymerOracleMapped } from "../../src/integrations/oracles/polymer/PolymerOracleMapped.sol";
import { OutputSettlerBase } from "../../src/output/OutputSettlerBase.sol";
import { MandateOutput } from "OIF/src/input/types/MandateOutputType.sol";
import { StandardOrder } from "OIF/src/input/types/StandardOrderType.sol";

/**
 * @notice EVM-side driver for the Base <-> Solana MAINNET Polymer e2e run.
 *
 * Mirrors the devnet BaseSolanaE2E.s.sol flow against the canonical mainnet
 * deployments. Entrypoints (select with --sig):
 *  - check()                    preflight: verify the write-once chain mapping and balances (no broadcast)
 *  - open()                     open the Base->Solana order, escrows USDC (leg 1)
 *  - receiveSolana(bytes)       submit the Polymer proof of the Solana submit to the oracle (leg 1)
 *  - finalise(bytes32,uint32)   finalise leg 1 after receiveSolana (solver bytes32, fill timestamp)
 *  - fill(bytes32)              fill the Solana->Base order output (leg 2)
 *
 * The order fields are sourced from env vars so the exact same order can be
 * rebuilt at finalise time and mirrored on the Solana side
 * (catalyst-intent-svm/mainnet-e2e). Timestamps are fixed values (not
 * block.timestamp) for the same reason.
 *
 * Required env:
 *  PRIVATE_KEY          uint     EVM key: user on leg 1, solver on leg 2
 *  E2E_EVM_ADDRESS      address  must equal vm.addr(PRIVATE_KEY); binds this
 *                                key to the identities committed in the
 *                                catalyst-intent-svm mainnet-e2e state
 *  E2E_SOLANA_RECIPIENT bytes32  mainnet recipient token-owner pubkey (leg 1)
 *  E2E_SOLANA_SOLVER    bytes32  mainnet solver pubkey (leg 2 fillerData)
 *  E2E_EXPIRES          uint32   leg-1 order expiry — generated by the prepare
 *  E2E_FILL_DEADLINE    uint32   step (now+24h / now+2h), NOT far-future: a
 *                                failed run must not strand the escrow
 * Optional env:
 *  E2E_AMOUNT (default 50000), E2E_NONCE
 */
contract BaseSolanaMainnetE2E is Script {
    // --- Base mainnet (canonical deployments, DEPLOYMENTS.md) ---
    InputSettlerEscrow constant INPUT_SETTLER = InputSettlerEscrow(0x1CC9260E285C2C8AC8D2E7102F3978056Ec1d0a8);
    OutputSettlerBase constant OUTPUT_SETTLER = OutputSettlerBase(0x52602D7cc3D833F5d28ee6D01C7F82C9b2322e10);
    PolymerOracleMapped constant ORACLE = PolymerOracleMapped(0x008C3800F3Ad9b3B662d002E90Cc00000000eE17);
    IERC20 constant BASE_USDC = IERC20(0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913);
    uint256 constant BASE_CHAIN_ID = 8453;

    // --- Solana mainnet identifiers (catalyst-intent-svm deployment, 13 Aug 2026) ---
    // LiFiBtfyPT1DnTHTAeZ2rwr5RgMrThwA5kt7KGT5nBV (oracle_polymer program id)
    bytes32 constant SOLANA_POLYMER_PROGRAM = 0x050cae5588f8d907500199177ab1239f61b8557af2ffacd5defed0070b858ad4;
    // DHShHmVkTwCzUzAQbCu4GDqJmursuDscNR6o4hTBgeRy (PDA "output_settler_simple" of LiFiEDFjz5x1jJe9gSXNDHQW4dWt4yLXdp2VN4EiQUt)
    bytes32 constant SOLANA_OUTPUT_SETTLER_PDA = 0xb68296ce230150bb20190a46eb26a198b05bec8fc7f0fa893d690cf531fa9e54;
    // EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v (mainnet USDC mint)
    bytes32 constant SOLANA_USDC = 0xc6fa7af3bedbad3a3d65f36aabc97431b1bbe4c2d2f6e0e47ca60203452f5d61;
    // Canonical LI.FI Solana chain id, as stored in the mainnet chain_id PDA.
    uint256 constant SOLANA_CHAIN_ID = 1151111081099710;
    // Polymer's protocol chain id for Solana.
    uint256 constant SOLANA_POLYMER_CHAIN_ID = 2;

    /// @dev Derives the acting wallet and asserts it is the address the
    /// Solana-side prepare step committed to (leg-1 solver identity and
    /// leg-2 output recipient both depend on it).
    function _wallet(uint256 pk) internal view returns (address wallet) {
        wallet = vm.addr(pk);
        require(wallet == vm.envAddress("E2E_EVM_ADDRESS"), "PRIVATE_KEY does not match E2E_EVM_ADDRESS");
    }

    function _amount() internal view returns (uint256) {
        return vm.envOr("E2E_AMOUNT", uint256(50000)); // 0.05 USDC
    }

    function _expires() internal view returns (uint32) {
        return uint32(vm.envUint("E2E_EXPIRES"));
    }

    function _fillDeadline() internal view returns (uint32) {
        return uint32(vm.envUint("E2E_FILL_DEADLINE"));
    }

    /// @dev The Base->Solana order (leg 1). Must be reproducible: every field
    /// is a constant or an env value, never block state.
    function _leg1Order(address user) internal view returns (StandardOrder memory order) {
        uint256[2][] memory inputs = new uint256[2][](1);
        inputs[0] = [uint256(uint160(address(BASE_USDC))), _amount()];

        MandateOutput[] memory outputs = new MandateOutput[](1);
        outputs[0] = MandateOutput({
            oracle: SOLANA_POLYMER_PROGRAM,
            settler: SOLANA_OUTPUT_SETTLER_PDA,
            chainId: SOLANA_CHAIN_ID,
            token: SOLANA_USDC,
            amount: _amount(),
            recipient: vm.envBytes32("E2E_SOLANA_RECIPIENT"),
            callbackData: hex"",
            context: hex""
        });

        order = StandardOrder({
            user: user,
            nonce: vm.envOr("E2E_NONCE", uint256(1)),
            originChainId: BASE_CHAIN_ID,
            expires: _expires(),
            fillDeadline: _fillDeadline(),
            inputOracle: address(ORACLE),
            inputs: inputs,
            outputs: outputs
        });
    }

    /// Preflight (run with plain `forge script`, no --broadcast): verifies the
    /// write-once oracle mapping and wallet funding before any value moves.
    function check() external view {
        uint256 mapped = ORACLE.chainIdMap(SOLANA_POLYMER_CHAIN_ID);
        console.log("oracle.chainIdMap(2):", mapped);
        require(mapped == SOLANA_CHAIN_ID, "Base oracle mapping [2 -> solana] wrong/missing");

        uint256 pk = vm.envUint("PRIVATE_KEY");
        address wallet = _wallet(pk);
        console.log("wallet:", wallet);
        console.log("wallet ETH:", wallet.balance);
        console.log("wallet USDC:", BASE_USDC.balanceOf(wallet));
        require(BASE_USDC.balanceOf(wallet) >= _amount(), "wallet needs USDC >= E2E_AMOUNT");
        console.log("preflight OK");
    }

    /// Leg 1 step 1: open the order on Base (escrows USDC).
    function open() external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address user = _wallet(pk);
        StandardOrder memory order = _leg1Order(user);

        bytes32 orderId = INPUT_SETTLER.orderIdentifier(order);
        console.log("user:", user);
        console.logBytes32(orderId);

        vm.startBroadcast(pk);
        BASE_USDC.approve(address(INPUT_SETTLER), order.inputs[0][1]);
        INPUT_SETTLER.open(order);
        vm.stopBroadcast();

        console.log("open() done. Record the orderId above in the run state.");
    }

    /// Leg 1 step 4: deliver the Polymer proof of the Solana `submit` tx to
    /// the Base oracle. Proof is the Prove API result decoded from base64 to hex.
    function receiveSolana(bytes calldata proof) external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(pk);
        ORACLE.receiveSolanaMessage(proof);
        vm.stopBroadcast();
        console.log("receiveSolanaMessage() done; attestation written on Base oracle");
    }

    /// Leg 1 step 5: finalise on Base after receiveSolana. The caller must be
    /// the SOLVER recorded in the Solana fill (InputSettlerEscrow requires the
    /// first solver as msg.sender) — with this harness that is the same wallet
    /// that opened the order.
    /// @param solver bytes32 proposed solver used in the Solana fill
    /// @param timestamp the fill timestamp recorded by the Solana fill
    function finalise(bytes32 solver, uint32 timestamp) external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address user = _wallet(pk);
        require(solver == bytes32(uint256(uint160(user))), "solver param is not this wallet");
        StandardOrder memory order = _leg1Order(user);

        InputSettlerBase.SolveParams[] memory solveParams = new InputSettlerBase.SolveParams[](1);
        solveParams[0] = InputSettlerBase.SolveParams({ timestamp: timestamp, solver: solver });

        vm.startBroadcast(pk);
        INPUT_SETTLER.finalise(order, solveParams, bytes32(uint256(uint160(vm.addr(pk)))), hex"");
        vm.stopBroadcast();

        console.log("finalise() done; escrow released to solver");
    }

    /// Recovery: refund the leg-1 escrow after `expires` has passed (rebuilds
    /// the identical order from env). Permissionless on-chain; inputs return
    /// to order.user.
    function refund() external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address user = _wallet(pk);
        StandardOrder memory order = _leg1Order(user);
        vm.startBroadcast(pk);
        INPUT_SETTLER.refund(order);
        vm.stopBroadcast();
        console.log("refund() done; escrow returned to user");
    }

    /// Leg 2 step 2: fill the Solana->Base order output on Base. The
    /// MandateOutput built here MUST byte-for-byte match the order opened on
    /// Solana (catalyst-intent-svm/mainnet-e2e/leg2-open.ts).
    /// @param orderId order id printed by the Solana open step
    function fill(bytes32 orderId) external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address wallet = _wallet(pk);

        MandateOutput memory output = MandateOutput({
            oracle: bytes32(uint256(uint160(address(ORACLE)))),
            settler: bytes32(uint256(uint160(address(OUTPUT_SETTLER)))),
            chainId: BASE_CHAIN_ID,
            token: bytes32(uint256(uint160(address(BASE_USDC)))),
            amount: _amount(),
            recipient: bytes32(uint256(uint160(wallet))),
            callbackData: hex"",
            context: hex""
        });

        bytes memory fillerData = abi.encodePacked(vm.envBytes32("E2E_SOLANA_SOLVER"));

        vm.startBroadcast(pk);
        BASE_USDC.approve(address(OUTPUT_SETTLER), output.amount);
        OUTPUT_SETTLER.fill(orderId, output, _fillDeadline(), fillerData);
        vm.stopBroadcast();

        console.log("fill() done; note the tx hash, block number, and log index for the Prove API request");
    }
}
